### ISSUE TITLE
Change Permissions & groups box on user's page

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#100]
Hey Aquib,

On the user's page we have a box with "Permissions and groups" with a settings link.

Since we're moving Permissions out of here, as per issue99, we're going to change this box too.

Please do the following:

1. Give the box a heading called `Group`
2. This box can now have a line in it like other boxes separating the heading & info
3. Display the group a user belongs to. On the right hand side of the group, put a blue link that says `Change`
4. The `Change` link will work similarly to the Reassign link in groups - it should open a modal where a new user group can be selected from a drop down.

**Comment by AquiburRKhan** [comment]
Doing this in branch `issue99`

**Comment by Cupofassam** [comment]
Works great  Aquib, thanks!

Realised it would be good to have a confirmation pop-up with some information.

After a user clicks reassign, show a confirmation pop-up with "back" and "Confirm" buttons.

On the popup please add this text:

`You are moving {user} from {current group} to {new group}. Configurations of the destination group such as account configurations, limits, fees etc will not be automatically applied to {user}.`

**Comment by Cupofassam** [comment]
👍
