### ISSUE TITLE
User & transactions columns - phase 2 - Sortable columns

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#104]
![image](https://user-images.githubusercontent.com/22153546/39750513-b88c0636-52b5-11e8-8cd0-5ac44973846c.png)

- When a user hovers over each Column header, it will be clickable. This will be indicated via the Column header highlighting on hover.
- Clicking the Column header will sort all users or transactions by that Column’s values. Initially the data will be descending - clicking on it again will trigger ascending.
- Clicking on a different Column header will sort by that Column instead.
- Default ordering will be descending dates. For users, date joined, for transactions, date created.
- Applies to both users list and transactions list.

**Comment by Cupofassam** [comment]
I like it a lot 👍 I think we just need some way of showing what the current sort is. Maybe change the arrow colour to black when you are sorting by that column? Open to suggestions here.

Also noticed a bug where it's only sorting the first page instead of the total results set. I looked at users and on the first page it shows the earliest user as joining on 17 April, but the earliest user join is actually 21 Feb, which I see if I go to page 3.

**Comment by AquiburRKhan** [comment]
waiting for this on the api side ?@sam

**Comment by AquiburRKhan** [comment]
fields to sort by in transactions:
```email , destination_transaction.user.email , tx_type , subtype , currency.code , amount , fee , status , id , created , total_amount , balance , account , user.username , user.identifier , updated , user.mobile_number , destination_transaction.id , source_transaction.id , label , reference , note , metadata```

fields to sort by in users:
```identifier , first_name , last_name , email , mobile_number , groups.name , created , updated , archived , status , kyc.status , active , last_login , verified , id_number , nationality , language , timezone , birth_date , username```

**Comment by Cupofassam** [comment]
AQ when you work on this next, please look into how the columns function. Josh would like to see if it's possible to POST to Rehive a list of the columns in an attribute named `fields`  e.g. `?fields=id,status,amount` 

So you're passing a list of fields you want to view and Rehive will return only those fields. This is only for the transactions list right now.

**Comment by Cupofassam** [comment]
Hey AQ

Here are the columns we can sort/order by:

reference
amount
fee
total_amount
balance
created
updated

**Comment by Cupofassam** [comment]
Thanks Aquib!

Works nicely. Please add this small tweak - any column which a user can sort, please change the label colour to dark blue instead of grey.

**Comment by Cupofassam** [comment]
The dark blue looks a bit weird - pls make it the same blue as this highlight

![image](https://user-images.githubusercontent.com/22153546/50643442-cc521600-0f76-11e9-847a-e7ad0079d200.png)

**Comment by Cupofassam** [comment]
👍
