### ISSUE TITLE
Transactions details pop-up does not update after saving

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#115]
Hey Aquib,

In the Transactions details popup, if I change the status of it and click save, the  status does not update. I have to close the modal, then the page refreshes, then if I open up the modal again it shows the correct status. Can we please make it so that the updated status is reflected in the modal is updated after clicking save.

**Comment by Cupofassam** [comment]
Thanks AQ, works great :) Bit of a side question, do you know why this drop down has these thick black lines on the left and the top and then no border on the right and bottom? Looks a bit weird, especially  since it overlaps ontop of the metadata box where there is no border or a thick border, and then suddenly the thin border of the metadata box.

![image](https://user-images.githubusercontent.com/22153546/42163134-a87ed986-7e01-11e8-852d-3b9e347126c0.png)

**Comment by AquiburRKhan** [comment]
![screenshot from 2018-07-02 19-58-29](https://user-images.githubusercontent.com/12262072/42168260-5226935e-7e32-11e8-81c7-56f8115d1a1e.png)


I dont know, for me it shows like this, no black border
