### ISSUE TITLE
Add shortcut to a account in transaction details modal

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#116]
Hey Aquib,

When there is an account reference in the transactions details modal, please make the reference a link to that account. 

![image](https://user-images.githubusercontent.com/22153546/40055523-7e5070ea-5848-11e8-9680-d755de133e74.png)

**Comment by Cupofassam** [comment]
Looks good Aquib :) Is there any way to scroll down to the account if a user has a lot of accounts on the page? This is not crucial but might be nice.

**Comment by AquiburRKhan** [comment]
Like, you dont want it to be filtered ? rather it should get scrolled to that account ?

**Comment by Cupofassam** [comment]
Didn't see the filtering, seems to be buggy, but I think filtering is better than scrolling so let's filter.

The filter is selected but it's not being applied - if I open filters and click "done" then it applies it.

![image](https://user-images.githubusercontent.com/22153546/42161007-93ec6414-7df9-11e8-807b-42e30622b8e9.png)

**Comment by Cupofassam** [comment]
Happy with this
