### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#136]
Hey Aquib,

Please investigate the versioning issue with the HTML requiring hard refreshes after deploys, we should not require hard refreshes.

**Comment by AquiburRKhan** [comment]
note from joshua:
Is this a possible fix for caching in angular:
```$stateProvider.state('stateName', {
   cache: false,
   url : '/url',
   templateUrl : 'template.html'
})```

**Comment by Cupofassam** [comment]
To test:

Run NPM install
Rrun the comman `gulp build`
Then in the `release` folder, in the `index.html` file check whether the js file number is changing or not when you change something in the code
it could be as simple as a console.log

**Comment by Cupofassam** [comment]
Seems to work :)
