### ISSUE TITLE
Verify page loads endlessly until user clicks

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#161]
Hey Aquib,

Noticed a bug now where if I register on the staging site, the verify page loads endlessly until I click. Happens in both Chrome and Firefox and in incognito mode.

Noticed the same thing after I have verified - if I click the continue button nothing happens until I click somewhere on the page again.

**Comment by AquiburRKhan** [comment]
Is this on the dashboard or the website? I couldnt reproduce the error in either places, maybe try hard refreshing before you test it again ? let me know if it still persists :)

**Comment by Cupofassam** [comment]
This is on https://staging.dashboard.rehive.com

So I register, and then I wait for the page to load where it tells me to go check my email for a verification email. Tested again and it's still just loading until I click.

There is definitely some weird issue going on with staging - like it logs me out because my session expired, but then doesn't let me log in again and keeps telling me my session expired until I hard refresh. Not sure if related

**Comment by Cupofassam** [comment]
This is fixed but there's an issue with registration.

I click continue without registration.
I click start 14 day trial.
It kicks me out saying admin access requires verification.

**Comment by AquiburRKhan** [comment]
please test this in issue87 , as it was in staging and staging had the sdk branch deployed in it

**Comment by Cupofassam** [comment]
cool this works
