### ISSUE TITLE
Exports highlight bug

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#162]
Hey Aquib,

On the exports, only the single latest export I have not looked at is highlighted green - all downloads which I haven't looked at should be highlighted.

**Comment by AquiburRKhan** [comment]
Hey sam, test this issue on master , didnt push the new branch as I didnt do any work on it

**Comment by Cupofassam** [comment]
Seems to be sort of working - I exported 3 files and the last 2 are highlighted. Closing this issue but want to keep an eye on it.
