### ISSUE TITLE
Replace current currency picker with new one

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#175]
Hey Aquib,

Please change the currency currency picker:

![image](https://user-images.githubusercontent.com/22153546/43410996-21e67bde-9429-11e8-9b37-d1d97e336be8.png)

With the new one which we used on Rewards:

![image](https://user-images.githubusercontent.com/22153546/43411197-c644bb1e-9429-11e8-8bc3-2b595fc423c9.png)

Is it possible to also add a search to the top of the list, below where the selections go?

The selectors need to be replaced on the following places:

- Build a fintech app - Adding currencies
- Build a fintech app - Accounts, adding currencies
- Dashboard - Currencies - Adding currencies
- Dashboard - Users - Add / Edit currencies to account
- Dashboard - Groups - Account Configurations - Add / Edit currencies on account configurations.

**Comment by Cupofassam** [comment]
Cool. This is so much better! Happy with it

**Comment by AquiburRKhan** [comment]
I changed the css for this, but we will know whether it is working or not only after deploying

**Comment by Cupofassam** [comment]
👍
