### ISSUE TITLE
Create interface for Stellar testnet service

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#178]
Hey Aquib,

Please make an interface for the Stellar testnet service. It's identical to the Stellar one and from an API point of view, but now admins can use friendbot instead of real Lumens.

Ping me or @ConnorMac if you have any questions

**Comment by Cupofassam** [comment]
https://stellar-testnet.services.rehive.io/

**Comment by AquiburRKhan** [comment]
fix debit and credit link in stellar cold storage and also in stellar service

**Comment by Cupofassam** [comment]
Feedback:

1. If I already have the normal Stellar Service added, and I add the Testnet Stellar Service, it didn't take me through the onboarding.
2. On the hot wallet onboarding, the bullet point, change the copy to (including the link):

> You can use the [Stellar friendbot](https://www.stellar.org/laboratory/#account-creator?network=test) to fund your hot wallet with testnet Lumens. Enter the address on the right into the Friendbot and click "Get test network lumens"

3. Warm storage, 2nd paragraph. Change copy to:

> You will need an active account on the Stellar testnet. Active accounts are accounts with at least 1 TXLM in them. You can generate a keypair via Stellar Labs [here](https://www.stellar.org/laboratory/#account-creator?network=test).

4. The Warm Storage bullet points,  please update to:

- Create an account on the Stellar testnet by generating a keypair on Stellar labs.
- You will receive a Public Key and a Secret Key. Store the Secret Key somewhere safe. If this key is lost you will lose the funds.
- Fund the account with at least 1 TXLM using the [Friendbot](https://www.stellar.org/laboratory/#account-creator?network=test). Confirm on the right when your account is funded.
- Add your Public Key to Rehive so its transactions can be tracked. Rehive does not have access to the funds.

**Comment by ConnorMac** [comment]
I've added hotwallet friendbot funding to the on boarding flow. I think for the warm storage since the user will need to go to the labs to generate the account lets leave out the fund page from it for the mo.
