### ISSUE TITLE
Can't upload company logo

### ISSUE THREAD

**Issue by IgorUsoltsev** [rehive/dashboard-angular#184]
Steps to reproduce:

1. Login to company account (I used `pxpay_demo`).
2. Go to Settings -> Upload logo.
3. Try to upload logo - 403 response from server, "Authentication credentials were not provided."

**Comment by Cupofassam** [comment]
Hi Ignor,

Thanks so much for logging this, our dev is looking into it now.

@AquiburRKhan while you are here, please move upload logo from the hive icon and move it into Company info rather.

**Comment by AquiburRKhan** [comment]
Will do :)

**Comment by Cupofassam** [comment]
Created a new issue (#185) for the field move. Pushing the big fix separately.

**Comment by Cupofassam** [comment]
This is now live.

**Comment by IgorUsoltsev** [comment]
Thanks guys this worked for me!
