### ISSUE TITLE
Notification templates overhaul

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#196]
Hi Aquib,

We are changing up the Notifications service.

1. The landing page is going to be Notifications instead of Settings. Please change the menu order to Notifications, Logs, Settings. 
2. We are also separating out Email notifications and SMS notifications. When on the Notifications list page, please add a left menu with the menu items "Email" and "SMS". The notifications list can remain the same, except Emails menu item will only show email notifications and SMS menu item will only show SMS notifications.
3. The Add notification page will be different. For email it will look like this: 

![notifications v1](https://user-images.githubusercontent.com/22153546/44042931-e3dd93aa-9f21-11e8-8cb4-834d82f4e09a.png)

**N.B. please change 2 things in the above image - make the order of the fields Template, Name, Description, Subject, Event, HTML message, Text Message enabled, to email, Expression, Preference enabled.**

So `SMS message` and `To mobile` fields will be removed for Email. I haven't made the SMS one but it should be straight forward - for SMS, remove `HTML message`, `Text message`, `To email`.

4. For the `HTML message`, `Text message` and `Expression` I want to add syntax highlighting. For that I want to use CodeMirror: https://codemirror.net/index.html

Please use this theme: https://codemirror.net/demo/theme.html#monokai 

5. We are adding a dropdown at the start of adding a notification called Template. Admins can select an email or sms template from the dropdown and it will populate all of the fields with template data. We're probably going to make it so that you request a template and the API sends the info back to you.

6. Under HTML message I have added a preview button. This should open up an iframe in a modal giving a preview of what the HTML will look like. It should just have a close button.

7. For HTML message and Text message we want to use CodeMirror's autocomplete feature. If a user pressed ctrl-space or types a { in `HTML Message` or `Text Message` it should show a dropdown list with parameters an admin can use. This will be based on the Event they chose. e.g. if they choose User Create -> https://docs.rehive.com/#create-user 

8. On the Notifications landing page, on the right of the "Add" button please add an `Add bulk` button. This should take the user to a page with all of the templates in a list with a checkbox next to each one. We can have a checkbox at the top which,w hen checked, selects all of them. 

We show everything available in "Data", so `id`, `first_name`, `last_name`, `email`, `username`, `id_number`, `birth_date`, `profile`, `currency`. All of the currency ones will be `currency.description`, `currency.code` etc

**Comment by AquiburRKhan** [comment]
Need a filter for notification for them to be filtered by `email` or `sms`

**Comment by Cupofassam** [comment]
`User create`

```json
{
        "id": "00000000-0000-0000-0000-000000000000",
        "first_name": "Joe",
        "last_name": "Soap",
        "email": "joe@rehive.com",
        "username": null,
        "id_number": "",
        "birth_date": "2000-01-01",
        "profile": null,
        "currency": {
            "description": "Rand",
            "code": "ZAR",
            "symbol": "R",
            "unit": "rand",
            "divisibility": 2
        },
        "company": "rehive",
        "language": "en",
        "nationality": "ZA",
        "metadata": null,
        "mobile": "+27840000000",
        "timezone": "Asia/Dhaka",
        "verified": true,
        "verification": {
            "email": true,
            "mobile": true
        },
        "verification": {
            "email": true,
            "mobile": true
        },
        "kyc": {
            "updated": 1509539801040,
            "status": "pending"
        },
        "status": "pending",
        "groups": [],
        "permissions": [],
        "created": 1464912953000,
        "updated": 1464912953000,
        "settings": {
            "allow_transactions": true,
            "allow_debit_transactions": true,
            "allow_credit_transactions": true
        },
        "last_login": null,
        "archived": false
    }
```

`User update`

```
{
    # same as above with 1 additional field:
    "original_user": {
        # same as normal user object.
    }
}
```

`User password reset`

```json
{
    "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
    },
    "uid": "{uid}",
    "token": "{token}",
    "url":"{url}"
}
```

`User password set`

```json
{
    "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
    },
    "uid": "{uid}",
    "token": "{token}",
    "url":"{url}"
}
```

`User email verify`

```json
{
    "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
    },
    "key": "{key}",
    "email":"{email}",
    "url":"{url}"
}
```

`User mobile verify`

```json
{
    "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
    },
    "key": "{key}",
    "mobile":"{mobile}",
    "url":"{url}"
}
```

`Address create`

```json

{
        "id": 2,
        "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
        },
        "line_1": "1 Main Street",
        "line_2": "East City",
        "city": "Cape Town",
        "state_province": "Western Cape",
        "country": "ZA",
        "postal_code": "8001",
        "status": "pending",
        "archived": false,
        "created": 1520929665311,
        "updated": 1520929665311
    }

```

`Address update`

```
{
    # same as above with 1 additional field:
    "original_address": {
        # same as normal address object.
    }
}
```

`Document create`

```json
{
        "id": 1,
        "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
        },
        "file": "https://url.to/file.pdf",
        "document_category": "other",
        "document_type": "other",
        "metadata": {},
        "status": "pending",
        "note": null,
        "archived": false,
        "created": 1520929665311,
        "updated": 1520929665311
    }
```

`Document update`

```
{
    # same as above with 1 additional field:
    "original_document": {
        # same as normal document object.
    }
}
```

`Bank account create`

```json
{
        "id": 2,
        "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
        },
        "name": "Bank Account",
        "number": "12341234",
        "type": "Cheque",
        "bank_name": "Bank",
        "bank_code": "1234",
        "branch_code": "1234",
        "swift": null,
        "iban": null,
        "bic": null,
        "code": "bank_account_000000000000",
        "status": "pending",
        "archived": false,
        "created": 1520929665311,
        "updated": 1520929665311
    }
```

`Bank account update`

```
{
    # same as above with 1 additional field:
    "original_bank_account": {
        # same as normal bank account object.
    }
}
```

`Crypto account create`

```json
{
        "id": 1,
        "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
        },
        "address": "0000000000000000000000000000000000",
        "code": "crypto_account_000000000000",
        "crypto_type": "bitcoin",
        "metadata": {},
        "status": "pending",
        "archived": false,
        "created": 1520929665311,
        "updated": 1520929665311
    }
```

`Crypto account update`

```
{
    # same as above with 1 additional field:
    "original_crypto_account": {
        # same as normal crypto account object.
    }
}
```

`Transaction create`

```json
{
        "id": "00000000-0000-0000-0000-000000000000",
        "tx_type": "credit",
        "subtype": null,
        "note": "",
        "metadata": {},
        "status": "Pending",
        "reference": null,
        "amount": 500,
        "fee": 0,
        "total_amount": 500,
        "balance": 0,
        "account": "0000000000",
        "label": "Credit",
        "company": "rehive",
        "currency": {
            "description": "Rand",
            "code": "ZAR",
            "symbol": "R",
            "unit": "rand",
            "divisibility": 2
        },
        "user": {
            "id": "00000000-0000-0000-0000-000000000000",
            "first_name": "Joe",
            "last_name": "Soap",
            "email": "joe@rehive.com",
            "username": null,
            "mobile": "+27840000000",
            "profile": null
        },
        "source_transaction": null,
        "destination_transaction": null,
        "messages": [],
        "fees": [],
        "archived": false,
        "created": 1476691969394,
        "updated": 1496135465287
    }
```

`Transaction update`

```
{
    # same as above with 1 additional field:
    "original_transaction": {
        # same as normal transaction object.
    }
}
```

Ignore transaction delete for now

**Comment by Cupofassam** [comment]
Hey AQ

My feedback:

1. Please shorten the file paths in the service - e.g. we don't really need things as long as `notificationServiceNotifications`, `createNotificationServiceNotification` and `createNotificationServiceNotificationMenu`

2. On the create notification page, there is no Email and SMS menu on the lefft.

3. The order of the fields on the create notification should be `Template, Name, Description, Subject, Event, HTML message, Text Message enabled, to email, Expression, Preference enabled.` Same for SMS except the sms-specific fields.

4. On notification create, Expression field needs to be much smaller as it has a limit on it - maybe make it only 2 lines tall. It can only be 150 characters (maybe we can show a character count-down?)

5. Preview button doesn't seem to be working, nothing happens.

6. Autocomplete options don't seem to be coming up with I type {

**Comment by Cupofassam** [comment]
Bulk notifications layout:

![bulk notifications v1](https://user-images.githubusercontent.com/22153546/46073618-b8cc2d80-c185-11e8-925a-ebac8895460b.png)

**Comment by Cupofassam** [comment]
Hey Aquib,

1. Tested the bulk upload - I have added all templates now. I think rather than listing all events, list all templates that have been added and display their template name instead of the event.

2. There seems to be a bug where it sets the event correctly  but all other fields are incorrect -  it seems to be using the last template I added. You can checkout my Wolfsrain company to see.

![image](https://user-images.githubusercontent.com/22153546/46304123-13162580-c5ae-11e8-8f0d-9ac79c8c82e2.png)

3. I see in notification edit the order of the fields is still the old one where events are at the bottom - please change this to be the same as create.
Edit also needs a preview button for the HTML.

4. Next to html message and text message fields please add `(Type { to see variable options for this event)`

5. Tried to add a new notification and when I looked at templates, it's not pulling all of the templates I added - I only see one. Is it maybe not updating the list when new templates are added?

6. In the html preview is there a way to remove the border around the text?

![image](https://user-images.githubusercontent.com/22153546/46304315-9c2d5c80-c5ae-11e8-84b5-5713b9e4c4f8.png)

**Comment by Cupofassam** [comment]
Thanks AQ :)

On the bulk adding templates page please decrease the width of the panel overall, too much white space. Line the bottom buttons' right side up with the right side of the check boxes (so move the buttons left).

![image](https://user-images.githubusercontent.com/22153546/46469548-0d018e00-c7d4-11e8-820d-c0312edbefc2.png)

**Comment by Cupofassam** [comment]
`Html Preview` modal heading should be `HTML preview`

Please also change the field name from `Html message` to `HTML message`

**Comment by Cupofassam** [comment]
Can we make the code backgrounds less black and make it the blue of the side bar?

**Comment by Cupofassam** [comment]
👍
