### ISSUE TITLE
Horizontal scrolling bar even on big screens

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#20]
Hey Aquib,
When in the dashboard I'm getting a horizontal scroll bar, even on my big 24" screen - please look into what's causing it and see if we can fix it to not scroll horizontally

Thanks!

**Comment by AquiburRKhan** [comment]
can you send me a screenshot please ? :)

**Comment by Cupofassam** [comment]
Sure thing :)
Chrome on a 24" screen:
![image](https://user-images.githubusercontent.com/22153546/36371007-7bab84e6-1569-11e8-9bd6-76d7e4376a84.png)

Firefox on a 21" screen:
![image](https://user-images.githubusercontent.com/22153546/36371047-9b5ecab4-1569-11e8-8668-4181ae7d003f.png)

Edge on a 24" screen:
![image](https://user-images.githubusercontent.com/22153546/36371087-c3c001da-1569-11e8-8d32-34cce9844c8c.png)
