### ISSUE TITLE
Dashboard consistency updates

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#203]
Hey Aquib,

I've been going through the dashboard looking at how we do various things and trying to make them more consistent. We have developed some good standards but I think we can apply them more consistently. What we set out in this issue will be the standard for things going forward (such as where modal exit icons are, close buttons, etc)

For modals I want the standard to be an x in the top right corner to close the modal. The action button to add etc on the bottom right. Remove 'close' buttons from the bottom left. 

Please make the following changes I've identified:

1. New transaction modal: add an x to the top right corner to close the modal. Make the "Next" button pale blue and not clickable until all required fields have been filled out.
2. Adding a new user - please make this screen open in a modal instead of on a separate page. Grey out the add button until all the required fields are filled.
3. Adding a new user - please add a label for the file upload. Call it `Profile picture`
4. Adding a new user - please change the wording of "Show more details" on the bottom left corner to "Advanced options".
5. Groups - please add a filter button on the top right of the Groups landing page. Users should be able to filter by group name.
6. Add group modal - please remove the close button from the bottom left. 
7. Add webhook modal - please remove the close button from the bottom left.
8. Please make the webhooks page look more like the transactions page. Get rid of the small "Webhooks" heading and replace it with a filter button. I'd like users to be able to filter by the column names - let me know if these filters need to be added by Platform. Instead of a text link please add the bluey green Add button. You can keep the "Edit" and "Delete" text links next to each item. 
9. Services - when adding a new service please make it open in a modal. It'll just have a dropdown where they select the service they want to add. (How easy would it be to let them add multiple services at once? Maybe with the currency selector-like input we implemented recently)
10. User - add account - remove the close button from the bottom left. Remove the "Currencies selected:" text - with the new selectors we no longer need  this as we show the selected currencies in the field. (Can you remove this everywhere please :P) 

![image](https://user-images.githubusercontent.com/22153546/44298692-ca4d2a80-a2e7-11e8-907c-16c0527c2e99.png)

11. In Groups -> Users -> Please swap the "Add" and "Refresh" button positions around and make the "Add" button the bluey green colour.
12. Add user to group modal - remove the close button from the bottom left
13. Tiers - add/edit Tier modal - remove the close button from the bottom left
14. Account configurations - add/edit modal - remove the close button from the bottom left
15. Company settings - Add Bank account - remove the close button from the bottom left (and the "currencies selected"
16. Rewards service. Get rid of the "Campaigns list" heading, Change the text "Add" to a button "Add". Please add a refresh button.
17. Rewards service. Campaigns list. Add a filter button to filter by campaign name or ID.
18. Rewards service - new reward modal - remove close button from bottom left
19. Notification service - Can we add filters hereto filter by name and event? Use a button Add instead of a text link Add. Please keep the select all checkbox.

**Comment by AquiburRKhan** [comment]
2 ) When adding a user , an admin can add a user without filling in any fields, so I didnt grey out the add button at the moment.

**Comment by Cupofassam** [comment]
Thanks Aquib! I am excited about this issue :P 

Feedback:

1. Anywhere we have advanced options (new transaction, new account for user, new user) , change 'Show less advanced options'/'Advanced options' to 'Hide advanced options'. Grammatically it should be show fewer options but I think that makes it too long, so hide works. (New txn doesn't have an option to hide the advanced options so we will need to add one). Please also make the spacing of this consistent - 

2. Anywhere we have advanced options (new transaction, new account for user, new user) please make it like "Add new user" where Advanced options is in line with the middle of the button. If you compare these two, on the add account modal advanced options is above the add button and there is a big space above the add button,underneath the currencies field:

![image](https://user-images.githubusercontent.com/22153546/46206567-accaa200-c324-11e8-8aa2-9303b1949d08.png)

**Comment by Cupofassam** [comment]
👍
