### ISSUE TITLE
Add mobile or user ID to transaction popup when no email address

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#218]
Hey Aquib,

On the transaction info modal, when the user does not have an email address, please show their mobile number and have it link to their user profile. If a user doesn't have an email address or mobile please show their user ID and link to their profile. Right now there is no quick way to get to a user from that modal unless they have an email address.

**Comment by AquiburRKhan** [comment]
Fixed this in master with the fix for the user account shortcut if user had no email

**Comment by Cupofassam** [comment]
👍
