### ISSUE TITLE
Getting immediately logged out after logging back in

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#219]
Hey AQ

Encountering this quite often.

I will go to the Dashboard and be logged out with the message `Authentication credentials not provided`

I enter my company, email password and login.

I immediately get logged out again saying my session has expired, even though it should be fresh again since I just logged back in...

When I log in for a second time it works.

**Comment by AquiburRKhan** [comment]
Taariq made a change in the sdk which should fix this, Let me know if you still face this issue after we merge it to master

**Comment by Cupofassam** [comment]
👍
