### ISSUE TITLE
Wrong company name and email displayed

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#23]
Hey Aquib,
A weird thing happened earlier. I was logged in on a demo account. Later on I noticed in the top right it was displaying testcompany and test1 instead of the demo account's details. I hard refreshed and then the correct details were showing. I can't manage to replicate the issue but it's very strange that this occurred. This is not urgent but sometime please investigate how this could happen.

**Comment by AquiburRKhan** [comment]
its a bug , fixed it :)
