### ISSUE TITLE
When creating a reward for a campaign, amount should send no value if none has been entered

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#231]
Hey Aquib

When creating a REWARD and a campaign is selected, currently, if a user does not enter an amount, the dashboard ends out 0 as a value for that field. This is overriding the campaign defaults, which would normally be applied to the amount field was left without a value. Please change it so that when creating a reward, and a campaign is selected,if no value is entered for `amount` field we do not send any value.

**Comment by AquiburRKhan** [comment]
please test this on staging

**Comment by Cupofassam** [comment]
on master

**Comment by Cupofassam** [comment]
Hey AQ

It seems that when making a new reward, we're getting a currency required error because dashboard isn't sending the campaign through in its response - pls double check this

**Comment by Cupofassam** [comment]
The other changes:

1. When creating a new campaign, a campaign can have both amount type fixed and percentage. Please change the dropdown for field Amount type to have Fixed, Percentage and Both. When Both is selected, 2 text boxes appear on the right - percentage should appear to the right of reward amount input box. These let reward_amount and reward_percentage to be set.

2. Please add the groups field back. Group data should be sent to the backend as CSV.

3. Please add an Event field - this will be the same as the Event list in Notifications. Users can select only one.

4. Please hide these fields beneath an 'Advanced options' link - group, max per user, visible, request, event

5. When issuing a reward, and a campaign is selected, and that campaign type is percentage or fixedpercentage, please make Amount a required field by showing a red *.

**Comment by Cupofassam** [comment]
Hey AQ

1. When I set Amount type to "Both" the 2 fields don't sit nicely on my screen -

![image](https://user-images.githubusercontent.com/22153546/45769364-b1fe6180-bc3f-11e8-91c7-ee043cb08571.png)

2. I noticed that when I set a group on a campaign and then go edit the campaign, I don't see the group there.

**Comment by Cupofassam** [comment]
👍
