### ISSUE TITLE
Export function should only export visible columns

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#233]
Hey Aquib,

We want exports to work differently.

When you select columns, it should impact the query of the page rather than just showing/hiding. So we want to call the query based on either the default columns we set for a new company or the saved selection of a user. As long as you're using this query it will affect the export - we want it to export only visible/queried columns.

`https://api.rehive.com/3/admin/transactions/?fields=id,tx_type,status` as an example, this url would return columns transaction id, transaction type and status and only return those 3.

**Comment by Cupofassam** [comment]
Happy with this - quick question though, is this also going to be on the users' transaction page, or do you have to go add it there?

**Comment by AquiburRKhan** [comment]
would have to go add it there
