### ISSUE TITLE
Allow users on users page to be right/middle clicked

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#242]
Hey AQ

Please allow users on users page to be right/middle clicked

Thx

**Comment by Cupofassam** [comment]
Cool - I see it right clicks and just opens, but can't middle click. What is the limitation with that?

Second, could we make the tab open in the background rather than the active tab pls :)

**Comment by AquiburRKhan** [comment]
https://stackoverflow.com/questions/6213807/open-a-new-tab-with-javascript-but-stay-on-current-tab

**Comment by Cupofassam** [comment]
Cool, this is better than not having it! Approved
