### ISSUE TITLE
Preserve filters?

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#243]
Hey Aquib

Is there a way to preserve a filter until I add a new one? I am encountering an annoying issue.

I want to add an account for every service user I have. I have 5 service users. I filter by group = service on the Users page. I can't open the users in a new tab each, so I have to click on them one at a time. Then I click back twice to get from users account page back to the users list page. When I get back there my filter is gone and I have to reapply it.

Is there a way we can preserve the filter selection until a user selects another or clears it?

**Comment by OdinsPlasmaRifle** [comment]
This is a test @Sam

**Comment by Cupofassam** [comment]
Hey Aquib,

Please add the following to anywhere where we have filters:

![image](https://user-images.githubusercontent.com/22153546/51141785-d0254880-1852-11e9-9a02-c616b58d2fc9.png)

Text will appear saying `Your results are currently being filtered` whenever a filter is applied.

Please also add a blue broder to the Filters button when there is an active filter. You can maybe experiment a bit here please.. with like a blueish shadow? Can try a couple of things you think may look good, just something subtle to make the button stand out a little.

**Comment by AquiburRKhan** [comment]
I experimented with borders , but it looked very off, so just kept your design

**Comment by Cupofassam** [comment]
Thanks AQ, looks good :)

I want to add another scenario where we need to preserve the filters:

On the dashboard when I do a transaction search with a bunch of filters and then do:
- click a transaction
- change the status
- confirm

Right now when I try this it doesn't keep my filters.

**Comment by Cupofassam** [comment]
Cool, that scenario worked nicely :) 

It seems that filters on the Users page remain even when I move off of the page, which is great. This doesn't seem to be the case for Accounts, Transactions, Webhooks and Request logs though. Please make is so that selected filters remain on those other pages even when clicking away from the pages.

Will this impact performance at all?

**Comment by Cupofassam** [comment]
👍
