### ISSUE TITLE
Add date format option in settings

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#244]
Hey Aquib

Low prio but something to add in time

In settings can you add an option for people to choose between US date format and rest of the world date format?

**Comment by michailbrynard** [comment]
"most of the rest of the world" date format it seems 😄 
 https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by Cupofassam** [comment]
Thanks Aquib

Pls change the text from `Company Date Format` to `Company date format`

**Comment by Cupofassam** [comment]
👌
