### ISSUE TITLE
Add user group as a filter option for users & transactions

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#25]
Hey Aquib :)

Johan added the ability to filter users & transactions by user groups

url../../?group={{group_name}}
url../../?group__isnull={{true|false}}

Please add this filter to the users & transactions pages

**Comment by AquiburRKhan** [comment]
`url../../?group__isnull={{true|false}}` , does this show users who are not in any groups ?

**Comment by crintus** [comment]
Yes, first one will filter users in groups or not

**Comment by AquiburRKhan** [comment]
`url../../?group__isnull={{true|false}}` not added in transactions list? Will add it in the future if it does get added

**Comment by Cupofassam** [comment]
Thx Aquib
Only 1 small change - change the drop down copy from "In group" to "In a group" please
