### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#268]
Hey Aquib :)

This applies to both group permissions and user permissions.

Platform has changed how we do permissions - there are now user permissions and admin permissions.

In both cases where users have default permissions, these should already be checked. Upon group creation these will be set by default if you run a create the batch permissions from a set list (chat to @crintus about this)

The OPTIONS regarding permissions have changed to the following (see permissions)
```
{
    ...
    "permissions": {
        "admin": {
            "group": {
                "CONNECT": null,
                "HEAD": null,
                "PUT": "change",
                "GET": "view",
                "POST": "add",
                "OPTIONS": null,
                "PATCH": "change",
                "TRACE": null,
                "DELETE": "delete"
            }
        }
    }
}
```

The 1st key is the section required (user/admin) the 2nd is the type of permission and the values are the level (add/change/..)

They can be styled in the same way, just separate them into Admin permissions and User permissions.

**Comment by AquiburRKhan** [comment]
@aquib and @sam This is relevant to you, Joshua already knows. After doing a permission migration test yesterday with a lot of data, we realized that the migration will take too long and require too much downtime to be viable. So the deploy is going to be postponed until I can figure out a way to migrate the permissions without any downtime

**Comment by Cupofassam** [comment]
Hey AQ

Please make sure that all permissions - admin AND user - are checked for admins, with the message saying they can't be changed. For service users none should be checked and none can be checked (on a group level).

Also to note: You currently have a couple permissions in the "user permissions" section that are not allowed for users. these permissions should be removed:
notification
request
service
transactionsubtypes

webhook
Those 5 should only be in the "admin permissions" section of the permissions page.

**Comment by Cupofassam** [comment]
I see it isn't correctly "checking" off the bank account, crypto account and transaction subtype permissions on user that have them. I think this is maybe because you are checking for `bank_account` instead of `bankaccount`

and the same for the others. New permissions don't have underscores.

**Comment by Cupofassam** [comment]
👌
