### ISSUE TITLE
Error when adding email address to new user who does not already have one

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#298]
Hey Aquib & Josh

If I create a new user without adding an email address during the create process, and then try to add an email, with "primary = true" it throws the following error:

![image](https://user-images.githubusercontent.com/22153546/47821155-68d61d00-dd68-11e8-9469-7c7926da3530.png)

Not sure where this error lies, platform or dashboard (probably platform?)

@OdinsPlasmaRifle

**Comment by AquiburRKhan** [comment]
@Cupofassam Joshua confirmed its a platform issue

**Comment by Cupofassam** [comment]
👍 Closing and wontfix-ing this.
