### ISSUE TITLE
Customizable user & transaction columns - Phase 1

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#30]
Hi Aquib, 
Please see the spec for customizable user & transaction columns below :) Shout if you have any questions:

# Dashboard - Enhancement - Customizable user & transaction columns

- Admin users would like the ability to choose which data columns to see on the users and transaction pages. 
- The dashboard will show a default selection of data columns which can be changed by an admin user. 
- Admin users can choose to deselect data columns and select additional ones. 
- If an admin user adds many columns, the dashboard will display a horizontal scroll bar to show the additional columns.
- Available user and transaction attributes and feature implementation phases are detailed below.

## User attributes

These are the user attributes available to us via the API. The ones which should appear as the default columns are in bold. 

Default attributes: **Identifier, First name, Last name, Email, Mobile number, Groups - name, Date joined.**

 Identifier |  First name |  Last name |  Email |  Mobile number |  Groups - Name
-- | -- | -- | -- | -- | --
**Date joined** | Status | KYC - Status | Active | Last login | Verified
ID Number | Nationality | Language | Timezone | Birth date | Username

## Transaction attributes

These are the transaction attributes available to us via the API. The ones which should appear as the default columns are in bold.

Default attributes: **User - Email, Type, Subtype, Currency - Code, Amount, Fee, Status, Created, Id**

 User -  Email |  Type |  Subtype |  Currency - Code |  Amount | Fee
-- | -- | -- | -- | -- | --
**Status** | **Created** | **Id** | Total amount | Balance | Account
User - username | User - identifier | updated | User - mobile number | Destination transaction - Id | Source transaction - Id
Label | Reference | Note | 

### Phase 1 - Select own columns

![image](https://user-images.githubusercontent.com/22153546/36659045-ca47dc90-1adb-11e8-859e-7b1343446836.png)

- Add a Columns button next to the Filters button.
- Clicking on the Columns button will show the Select columns menu.
- Users can search through available attributes.
- Ticked boxes indicate currently displayed Columns
- Users can select or deselect Columns as required.
- Clicking the “Restore defaults” link will restore the original list of defaults.
- Clicking the “Done” button will apply a user’s selection.
- Applies to both users list and transactions list.

**Comment by Cupofassam** [comment]
Thanks Aquib. When Groups Management is done please:

1. Apply this functionality to transactions
2. Ensure that saved column selections are per user per company. (Right now if I select columns, log out and create a new company, my previous selection is there rather than default. Default selection should be present for new companies).

**Comment by Cupofassam** [comment]
Thanks Aquib, happy with this :)

**Comment by Cupofassam** [comment]
Tested this on production. The only thing not working is it's not saving the columns selection per user per company. I selected only 3 columns for users on one account, logged out, made a new account, and the new account had the previous account's selection instead of the default values.

**Comment by AquiburRKhan** [comment]
I just did the same thing, its working properly in production for me , can you please test it again :) , I selected 3 columns , then logged out, registered a new company , this company was showing default columns, selected 1 single column, logged out , went back and forth between each company and the choices persisted

**Comment by Cupofassam** [comment]
Tested on production again and got the same error - let's Skype and screenshare on Monday and see if we can work it out :)
