### ISSUE TITLE
Notification service - update sorting

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#302]
Hey AQ

We're going to display email and SMS notifications a bit differently by sorting them by event type.

It should look something like this:

![image](https://user-images.githubusercontent.com/22153546/48152988-e43a5000-e2cd-11e8-9aa8-a545bdb6b312.png)

Please sort everything alphabetically.

The event groups and headings are as follows:

Address
- Address create
- Address update

Bank accounts
- Bank account create
- Bank account update

Crypto accounts
- Crypto account create
- Crypto account update

Documents
- Document create
- Document update

Transactions
- Transaction create
- Transaction delete
- Transaction execute
- Transaction initiate
- Transaction update

Users
- User create
- User update
- User password reset
- User password set
- User email verify
- User mobile verify

**Comment by Cupofassam** [comment]
Thanks AQ :)

I think let's put the column order back the way it was with Name first - so it should be:

Name, Subject, Enabled, Event

Another thing I want to try: please get rid of the left menu with "Email" and "SMS"

Rather put a tier 2 menu underneath Notification Service heading for Email and SMS

**Comment by Cupofassam** [comment]
Thanks AQ, I like it

I think we just need to adjust the column spacing a bit. There is a large space after Enabled checkboxes and Event, but then Name and SUbject are cramped together. PLease move Enabled and Event more left, increase the width of the space available to the Name and Subject fields. 

The spacing before and after Enabled and Event should be about equal, so we don't have huge spaces on either side

![image](https://user-images.githubusercontent.com/22153546/48482680-0b3ad980-e81a-11e8-8acb-d3573c0fc95d.png)

**Comment by AquiburRKhan** [comment]
random issue comment
