### ISSUE TITLE
Accounts move

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#31]
Hey Aquib,

On a User's Details page, please move the "Accounts list" onto a User's Accounts page instead. It can go above the boxes that currently list each account's currencies.

Please remove the boxes that show the accounts and their currencies from the User's Details page. It can stay on the accounts page.

![image](https://user-images.githubusercontent.com/22153546/36671725-6eb95e2e-1b05-11e8-9292-ffe67703696c.png)

**Comment by AquiburRKhan** [comment]
so there will be nothing related to accounts on the user detail's page ? all the accounts related stuff will be in the accounts page ?

**Comment by Cupofassam** [comment]
correct

**Comment by Cupofassam** [comment]
Further to this, in this "Add account" pop up please add a currency selector under the Primary checkbox

![image](https://user-images.githubusercontent.com/22153546/36715793-663f2e40-1ba0-11e8-80f5-8b3ffa411e28.png)
