### ISSUE TITLE
Add code mirror to company info page for company config field

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#310]
Hey AQ

Please implement code mirror on the company configuration field on the Company Info page - it should be able to format nicely for json 

Also whenever I load pages throughout the dashboard I get a lot of 404s for codemirror, please fix those

**Comment by Cupofassam** [comment]
Cool :)

Just to double check, this has the old bug where if you save it overrides it, that ill be fixed when we merge this to master, if the issue with the fix in it is also merged, right?

**Comment by AquiburRKhan** [comment]
yep , it should

**Comment by Cupofassam** [comment]
👌
