### ISSUE TITLE
Add Sendgrid/ Twilio fields to the notification service

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#311]
Hey Aquib

In the Notification service we're going to add something to let admins add their own sendgrid or twilio details.

1. In the Notification Service -> Settings -> Company info, please add 2 buttons. `Add SendGrid details` and `Add Twilio details`.

2. The field `credential_type` is how we know whether we're setting SendGrid or Twilio. for SendGrid the value to send through is `sendgrid` and for Twilio it's `twilio`

3. If a user clicks a button please open a modal where they can add the details (info below). Once they have been added you can add them to the Company info panel - it can just have a heading in bold text (Like "Company info") and then displaying the field names and the values users entered.

4. On the bottom right of each set of fields please add a button that says `Remove Twilio details`/`Remove SendGrid details`

5. If the value is `twilio` - there's a field called `credentials` and this field should contain a JSON object that contains 3 subfields: `twilio_sid`, `twilio_token`, and `twilio_from_number`.

```
{
    "credential_type": "twilio",
    "credentials:" {
        "twilio_sid": "",
        "twilio_token": "",
        "twilio_from_number": ""
    }
}
```

If the value is `sendgrid` - there's a field called `credentials` and this field should contain a JSON object with 2 subfields: `sendgrid_api_key` and `sendgrid_from_email`

```
{
    "credential_type": "sendgrid",
    "credentials:" {
        "sendgrid_api_key": "",
        "sendgrid_from_email": ""
    }
}
```

**Comment by AquiburRKhan** [comment]
Sam: so like the edit button is fine but we could move the delete button to the heading, on the right
and make it say remove
and then also disable the link to add more, when one is present

**Comment by AquiburRKhan** [comment]
the whole credential has to be sent for the `credentials` field.

**Comment by Cupofassam** [comment]
👍
