### ISSUE TITLE
Make x image not blurry

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#326]
Hey Aquib

In the multiselector field, when there is a currency selected the X to remove it quite blurry, please see if you can improve it on 4k screens

![image](https://user-images.githubusercontent.com/22153546/49736072-c9bf1200-fc91-11e8-8684-f12a84e07f1e.png)

**Comment by Cupofassam** [comment]
Nein, still blurry :P

**Comment by Cupofassam** [comment]
I have asked Nina to make a higher res version of the sprite for us

**Comment by Cupofassam** [comment]
Still blurry 😵

**Comment by Cupofassam** [comment]
Nope still blurry :P 

Any other ideas? Last Aquib said is he needed Nina to make it the exact size, as this one isn't.

**Comment by Dblaze47** [comment]
I am seeing no other ways to fix this until I receive the correct  sprite with size as Aquib asked for from Nina. Once the high res sprite is received, it's an easy change.

**Comment by Cupofassam** [comment]
What if we got rid of the sprite image and added an icon?

**Comment by Cupofassam** [comment]
Looks better - more crisp, but it's out of bounds of the button

![image 10](https://user-images.githubusercontent.com/22153546/52974633-dfa42e00-33ca-11e9-9ba7-0fed170d095e.png)

**Comment by Cupofassam** [comment]
👍
