### ISSUE TITLE
Populate user group on accounts page

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#333]
Hey AQ

Josh has implemented that we can now get user group on the accounts page. It has been deployed. When I go to the page I'm not seeing any user groups listed, so thinking we just haven't implemented it yet.

Please make it display the user group :)

**Comment by Cupofassam** [comment]
Thanks Aquib :)

Quick question, will the user group column show/be selected by default?

**Comment by AquiburRKhan** [comment]
currently yes
