### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#340]
Hey Aquib

In another issue I ask for you to create a Developers menu item. You can do this issue first and put this link in the Developers section as a submenu called `Access control`

```

Access control rules have been added - they are in the admin API to allow admins to limit access to the whole company, a specific group, or a specific user.

A  list of access controls rules can be retrieved (there is only one type of rule atm: `ip`). Each access control rule can have an action of `deny` or `allow`. In addition an access control rule can be attached to a specific user or a specific group.

Access control rules can be "added", "updated" and "deleted".  The value of the `IP` type rule (the only type atm) should  be a single IP or a `*` wildcard that represents "all IPs".

```

Please create a section like the Webhooks page where we can add, edit, view and delete these rules. When adding a rule these are the fields users need to fill in:

- `type` - REQUIRED - string - right now there is only one type which is "IP" - please make this a radio button.
-`action` - REQUIRED - string - values can be `allow` or `deny` - please make these choices radio buttons.
- `value` - REQUIRED - string - this will  be the IP address a user fills in.  No validation on this. They can only enter one IP, not a range. Please make the help text `Please enter a single IP address.`
- `label` - string - just a description.
- `user` - user identifier (email/mobile/id/username , this is returned as a user object once saved)
- `group` - group identifier (this is returned as a group object once saved)

A rule can only be applied to a user OR a group, not a user and a group. Please make it a radio button to select between user and group,  and then have a search field where they can search for one to select. The help text will be `Search for a user/group to apply this rule to`

*Endpoints*
GET/POST : https://api.rehive.com/3/admin/access-control-rules/ - create or get a list of access control rules
GET/PATCH/PUT/DELETE : https://api.rehive.com/3/admin/access-control-rules/<id>/ - get, update or delete a single rule.

Ping me and @OdinsPlasmaRifle if you have any questions :)

**Comment by Cupofassam** [comment]
Thanks Aquib!

Small tweaks:

1. Change "Search for a user/group to apply this rule to" to "Search for a user or group to apply this rule to"
2. Change the Value field's help text to "Enter a single IPv4 or IPv6 address".
3. Add a little " i " next to the Value field label. Its help text can be:

```
IPv4 address format e.g. 19.117.63.126
IPv6 address format e.g. 2001:db8:3333:4444:5555:6666:7777:8888
```

**Comment by AquiburRKhan** [comment]
Its under developers section now

**Comment by Cupofassam** [comment]
Awesome :)

1. Please make the Value's "i" help block a little longer so that everything sits on one line

2. Please change the placeholder text of the "Search for a user or group to apply this rule to" field, where user is selected, to
`Please enter an email, mobile number, id or username`.

3. Please change the field name "Search for a user or group to apply this rule to" to "Enter a user or group to apply this rule to"

**Comment by Cupofassam** [comment]
Also please remove the full stop at the end of the help text for Value

it should end with `8888` not `8888.`

**Comment by Cupofassam** [comment]
👌
