### ISSUE TITLE
refactor date functions in transactions , users ,etc

### ISSUE THREAD

**Issue by AquiburRKhan** [rehive/dashboard-angular#343]
refactor date functions in transactions , users ,etc

**Comment by AquiburRKhan** [comment]
Will also refactor reference filter and amount filters

**Comment by AquiburRKhan** [comment]
To test this, please test all the filters which has dates, amount and reference

**Comment by Cupofassam** [comment]
Seems account name filter doesn't work properly on transactions (on live or on this branch)

- [ ] 1. When I search transactions for account ref ZRSJRYFGL8 only pending transactions show up, it should give me all related transactions.

- [ ] 2. Change "Account" filter on transactions to "Account reference"

**Comment by Dblaze47** [comment]
![selection_001](https://user-images.githubusercontent.com/18096268/52617220-57eb8a80-2ec5-11e9-8b3d-527640b64bd1.png)

**Comment by Cupofassam** [comment]
👍
