### ISSUE TITLE
Rewards service - change account dropdown to a search

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#387]
Hey Manosh :)

When creating or editing a reward campaign we currently get all accounts so a user can select one to use.

This makes the page very slow though. Please change that input from a dropdown where we get all accounts to a search that lets users search for and then add an account.

**Comment by Cupofassam** [comment]
Thanks M, this works well. Small styling tweaks:

![image](https://user-images.githubusercontent.com/22153546/52309885-27c65800-29aa-11e9-9cf5-1ea222fea232.png)

- [ ] 1. Please make the blue squiggle the same spacing as the green squiggle. 

- [ ] 2. Change the field label from `Account` to `Select reward account`.

- [ ] 3. After an admin enters a user and their accounts appear, please put a field label above that drop down field called `Accounts`

- [ ] 4. I see when I have an account selected there is a little `x` on the right. To me it doesn't make sense to have this here because I can only have one thing selected in the drop down (or I should only be able to). Please hide the `x` - if an admin wants to change it they can just choose from the drop down.

I know you specifically asked me about this and I said just make it the user, so no need to implement this, I just want a time estimate - how long would it take to make that field search users and account references as well?

**Comment by Dblaze47** [comment]
As for the field to search user as well as account references, you can see that when the accounts dropdown appears, it comes with search bar to filter using account name/reference. If that is not sufficient, I will need to introduce another dropdown to the left that will let admins choose between searching for user email/account reference in the field, and then load the accounts as per query. It will not take more than a few hours, but will be performance heavy.

**Comment by Cupofassam** [comment]
Thanks M :)

We'll see if in future we need to add a search by reference, for now by user is good 👌 This can be merged
