### ISSUE TITLE
Move "Notifications" section in Settings + other settings tweaks

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#409]
Hey M

In the Settings section in a company, there is a submenu called Notifications:

![image](https://user-images.githubusercontent.com/22153546/52427121-05e2e780-2b08-11e9-8351-949703d26a6a.png)

This was going to be a much more comprehensive system, which is why it has its own section, but then it morphed into the Notifications Service instead. So now it's a bit weird to have this whole section just for 2 options.

I want to move these and also do some other tweaks in settings.

- [x] 1. Please get rid of the "Notifications" left submenu on the Settings page

- [x] 2. Please move the 2 notifications settings onto the Company settings page. 

- [x] 3. Change those 2 checkboxes to toggles instead. They should be toggled as on by default.

- [x] 4. Change the field labels: 

"Account password reset notifications" to "Send password set/reset notifications"
"Account verification notifications" to "Send email/mobile verification notifications"

- [x] 5. Add an "i" icon next to these 2 settings. Where you see words inside { } brackets please make it a link. Their text:

Send password set/reset notifications:

```
Sends password set and reset notifications to users.
To use a custom page for password set and reset, add your custom page URLs on the {Company info} page.
To send these notifications from your company's email address, enter a company email address on the {
Company info} page.
To override these emails entirely with your own custom emails, activate the {Notification Service}.
```

Send email/mobile verification notifications:

```
Sends email and mobile verification notifications to users.
To use a custom page for email verification, add your custom page URLs on the {Company info} page.
To send these notifications from your company's email address, enter a company email address on the {
Company info} page.
To override these emails entirely with your own custom emails, activate the {Notification Service}.
```

- [x] 6. On the Company Info page, add an "i" next to the Company email field. The help text can be:

`If this field is filled in, password set/reset notifications and email verification notifications will be sent from this email address. You can override this by enabling the {Notification Service} if you want your emails to send from an email address which is different to your company email address. `

- [x] 7. On the Company Info page change "Email confirmation url" to say "Email verification url"

- [x] 8. If a user tries to disable either "Send password set/reset notifications" or "Send email/mobile verification notifications", show a warning modal with this text:

Send password set/reset notifications:

**Title:** Warning
**Description:** You are about to disable sending password set/reset notifications to users. Unless you have added custom emails in the {Notification Service}, manually added-users will not be able to set their password and no users will be able to set their password. Are you sure you want to continue?

Send email/mobile verification notifications:

**Title:** Warning
**Description:** You are about to disable sending email/mobile verification notifications to users. Unless you have added custom emails in the {Notification Service}, users will not be able to verify their email addresses or mobile numbers. Are you sure you want to continue?

**Comment by Dblaze47** [comment]
- [] 9. Align the tooltip contents to left.

**Comment by Cupofassam** [comment]
Thanks M :)

My feedback:

- [ ] 1. When I click on Settings in the left menu, right now I land on the settings page but with no page displaying, just the secondary left menu. Please make the `Company info` panel be open by default.

- [ ] 2. I noticed on the tooltips I can't click links because they disappear lol. I think we can remove the links, people will figure it out (same for the link in the Company email tooltip on the Company info page). On the Send password notifications tooltip there are 2 missing spaces - one between 'the' and 'company' (3rd paragraph) and one between 'the' and 'notification" (4th paragraph),

- [ ] 3. Can we make the tooltips for the two send notifications settings a bit wider? They have ended up very long. Maybe 50% wider.

**Comment by Cupofassam** [comment]
👍
