### ISSUE TITLE
Make Rehive logo link to Rehive website

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#415]
Hey M

Please make the logo on the top left link to our website, both when logged out (so on login/register screens) and logged in. 

https://rehive.com/

**Comment by Dblaze47** [comment]
Currently on the company setup page, the logo acts as  a means to go back to currencies page. So I am going to keep it on the setup page, and on the dashboard as well as the login screen I am going to make it redirect to Rehive site.

**Comment by Cupofassam** [comment]
👍
