### ISSUE TITLE
Improve add currencies

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#43]
Hey Aquib, I want to improve the way we add currencies, current flow is a little odd.

![image](https://user-images.githubusercontent.com/22153546/37421160-473c1594-27c1-11e8-9e56-5c96489f3af1.png)

When an admin clicks "Add currency", this should open in a pop-up:

![image](https://user-images.githubusercontent.com/22153546/37421191-582cd0c8-27c1-11e8-81ca-4f3a7c894dbf.png)

If an admin clicks "Add custom currency", the pop-up's contents should be replaced with the custom currency adding fields:

![image](https://user-images.githubusercontent.com/22153546/37421214-68a631ec-27c1-11e8-8037-0a0fdc9726a1.png)

After a currency is added, display a message in the bottom right corner saying Currency was successfully added.

Shout if you have any questions

**Comment by Cupofassam** [comment]
Thanks Aquib :)

2 things:

1. Please add a modal after successfully adding a currency that displays info like this:

![image](https://user-images.githubusercontent.com/22153546/38902045-0c659492-429f-11e8-88f8-c532fb8e22c8.png)

If they added 1 currency, the copy can be:

`You have successfully added currency <currency> to your dashboard.` 

and then the code, description etc. below.

If they added 2 or more currencies:

`You have successfully added currencies <currency1>,<currency2>, and <currency3> to your dashboard.`

Then you can list each one's details in order below.

The button to continue can say `Got it!`

2. Please hide from the selection list any currency I have already added.

**Comment by Cupofassam** [comment]
Feedback:

1. Please make the selected currencies be bold:

![image](https://user-images.githubusercontent.com/22153546/38936540-4cddf488-4321-11e8-8ad4-02fa4d3c6611.png)

2. Please make the "and" not bold when listing currencies:

![image](https://user-images.githubusercontent.com/22153546/38936597-6e411aba-4321-11e8-9197-ba247286390c.png)

3. I want to change the modal showing the info slightly. I want to make this a confirm page rather, a bit like the current one. The copy at the top can be:

`You are adding currencies <currency1>, <currency2>, and <currency 3> to your dashboard.`

The button can say `Confirm` instead of `Got it!`

Please put the code, description, symbol, unit, divisibility closer together (maybe use the same spacing as for the user info at the top of a user's page?) and put a thin border around the group of info and maybe a soft background colour. 

![image](https://user-images.githubusercontent.com/22153546/38936762-d1da7a8a-4321-11e8-8515-fd61f2fc9a77.png)

**Comment by Cupofassam** [comment]
Cool! Confirmation modal feedback:

1. The old copy is still there, pls switch it to:

`You are adding currencies <currency1>, <currency2>, and <currency 3> to your dashboard.`

2. Please put a small space between the boxes.

3. Please make the boxes a bit shorter

![image](https://user-images.githubusercontent.com/22153546/38941018-e613c880-432b-11e8-870a-92e92cda08cb.png)

**Comment by Cupofassam** [comment]
Decided to remove the boxes, looks a bit weird. And please add a back button by Confirm so they can go back and change their minds.

**Comment by Cupofassam** [comment]
And change the copy to `You are adding currencies <currency1>, <currency2>, and <currency 3> to your company.`

**Comment by Cupofassam** [comment]
Awesome Aquib :)

One small thing I noticed - I got a validation error when trying to confirm adding my custom currency.  It said that the currency codes may only contain upper-case alphanumeric letters. 

Can you please trigger any validation errors like this on the add custom currency modal itself when a user clicks "add"? It shouldn't tell a user so late and then force them to go back to the modal.

Another bit of feedback: When adding a custom currency, the heading at the top says "Add currency". Please make it say "Add custom currency"

**Comment by AquiburRKhan** [comment]
What do you think about making the input for custom currency code to always be uppercase , like we lowercase group names ?

**Comment by Cupofassam** [comment]
I like it, let's do that.

**Comment by Cupofassam** [comment]
👍
