### ISSUE TITLE
Demo button

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#430]
Hey M :)

Please create a new page on the following url:

https://dashboard.rehive.com/#/demo

This page will have only the following:

- [x] 1. Rehive logo on the left

- [x] 2. Header showing my email, company name and the profile button.

- [x] 3. A purple button in the middle of the page (maybe 3x the size of our normal buttons?) that says "Setup demo"

- [x] 4. When the button is clicked, it can show Text in the centre of the screen saying "Setting up demo..." with a spinner beneath it. Spinner can be 2x the normal size. Text can be the size of the headings on pages like Notification Service. Once all the API calls are done you can redirect to the currencies page.

This button is going to do a bunch of setup in the background. Please make it do the following:

### Groups

- user - _default_ - _public_
- manager
- support
- merchant

**Group descriptions:**

Group | Description
-- | --
admin | Admin users have full access to all aspects of the company.
service | Services have access to specific permissions that’s needed for each service.
manager | Managers have access to make transactions from their own operational account, view and verify user data. Managers do not have access to  system configurations.
support | Support has limited access to make transactions from their own operational account, view and verify user data. Support do not have access to  system configurations.
user | Users are limited to their own accounts.
merchant | Merchants are limited to their own accounts.

### Services

- Notification Service
- Bitcoin Testnet Service
- Rewards Service
- Stellar Testnet Service - _When Activating the Stellar Service, take the hot wallet public key and use it as the warm wallet public key and the issuer address for the custom asset._
- Product Service
- Batch Send Service

### Currencies

- `TXBT` (added automatically by the Bitcoin Testnet Service)
- `TXLM` (added automatically by the Stellar Testnet Service)
- An asset on Stellar called `DEMO` (the Issuer account should be the same public address as the hot wallet)

### Currency and account configurations

Account | Types | Group | Currency 
-- | -- | -- | -- 
operational | Default, primary | admin | TXBT, TXLM, DEMO 
operational | Default, primary | manager | TXBT, TXLM, DEMO 
operational | Default, primary | support | TXBT, TXLM, DEMO 
wallet | Default, primary | user | TXBT, TXLM, DEMO

### Subtypes

Name | Type | Description
-- | -- | --
issue | credit | Subtype is used to issue funds to the destination address when issuing crypto assets.
fund | credit | Subtype is used to funds operational accounts.
deposit | credit  | Subtype is used to credit the destination account balance for a deposit transaction.
deposit | debit  | Subtype is used to debit the source account balance for a deposit transaction.
withdraw | debit | Subtype is used to debit the source account balance for a withdraw transaction.
send | debit | Subtype is used to debit the source account balance for a transfer transaction.
receive | credit | Subtype is used to credit the destination account balance for a transfer transaction.
reward | credit | Subtype is used to credit the destination account balance for a rewards transaction.
reward| debit | Subtype is used to debit the source account balance for a rewards transaction.
purchase | credit | Subtype is used to credit the destination account balance for a purchase transaction in the marketplace or in store.
purchase | debit | Subtype is used to debit the source account balance for a purchase transaction in the marketplace or in store.
mass_pay | debit | Subtype is used to debit the source account balance for bulk transfer transactions.
mass_pay | credit | Subtype is used to credit the destination account balance for bulk transfer transactions.

### Tiers

These tiers should be setup on the `user` group:

Tier 1 | Tier 2 
-- | --
--- | Basic | Intermediary
--- | First name, Last name | First name, Last name, Verified email

Limits: 
- Tier 1 - 1,000 max monthly limit  for all currencies.
- Tier 2 - 10,000 max monthly limit for all currencies.

These should be on the `merchant` group:

Tier 1 | Tier 2 
-- | --
--- | Basic | Intermediary
--- | First name, Last name | First name, Last name, Verified email

Limits: 
- Tier 1 - 1,000 max monthly limit  for all currencies.
- Tier 2 - 10,000 max monthly limit for all currencies.

### Company configuration

Please add this as the Company configuration:

```
{
    "company": {
        "name": "CompanyName",
        "id": "CompanyId",
        "description": "CompanyName is a multi cryptocurrencies app for spending online."
    },
    "auth": {
        "mfa": "",
        "username": false,
        "email": "",
        "terms": [],
        "identifier": "email",
        "mobile": "",
        "country": false,
        "pin": "",
        "first_name": false,
        "last_name": false
    },
    "design": {
        "app": {
            "surface": true,
            "tabBarLabels": false
        },
        "notifications": {
            "actionButtonsType": "contained",
            "layout": "material"
        },
        "wallets": {
            "balance": "badge",
            "actionButtonsType": "",
            "layout": "mini",
            "showActions": false,
            "headerColor": "font",
            "header": "",
            "headerActionType": "text"
        },
        "home": {
            "header": "wallets",
            "content": [
                "notifications",
                "rewards",
                "wallets"
            ]
        },
        "other": {
            "floatingActionButtons": false,
            "actionButtonsType": "text",
            "homeCardLayout": "material"
        },
        "campaigns": {
            "actionButtonsType": "contained",
            "layout": "material",
            "showActions": true
        },
        "general": {
            "elevation": 2,
            "shadow": 3,
            "cornerRadius": 5
        },
        "buttons": {
            "elevation": 4,
            "shadow": 10,
            "bold": false,
            "rounded": true
        },
        "cards": {
            "elevation": 3,
            "shadow": 8,
            "actionButtonsType": "contained",
            "cornerRadius": 20
        },
        "popUp": {
            "cornerRadius": 20
        }
    },
    "cards": {
        "home": {
            "custom": [
                {
                    "dismiss": true,
                    "image": "blocks-card",
                    "title": "Welcome to CompanyName",
                    "id": 0,
                    "description": "Multi-currency app for online payments and rewards."
                }
            ]
        }
    }
}
```

### Reward campaigns

Create 2 campaigns:

- [x] 1. Just for Joining

- Campaign name: Just for joining
- Campaign description: You have received 20 Demo tokens for registering!
- Currency: `DEMO`
- Start date: current date
- End date: current date + 1 month
- Reward total: 5000
- Amount type: Fixed
- Amount - 20.00
- Visible - true
- Request - false
- Account - Choose the operational account for the admin user
- Campaign status: Active
- Max per user: 1
- Event: `user_update`

- [x] 2. First 250 users

- Campaign name: First 250 users
- Campaign description: The first 250 users to claim this reward get and additional 10 DEMO tokens.
- Currency: `DEMO`
- Start date: current date
- End date: current date + 1 month
- Reward total: 2500
- Amount type: Fixed
- Amount - 20.00
- Visible - true
- Request - true
- Account - Choose the operational account for the admin user
- Campaign status: Active
- Max per user: 1
- Event: none

### Product service

Create 2 products:

- [x] 1. Steam voucher

- Product name: Steam voucher
- Product description: $10 Steam voucher
- Quantity: 100
- Product type: voucher
- Code: STEA10
- Prices:
Price1: Currency - DEMO, amount - 5
Price2: Currency - TXBT, amount - 0.002
- Enabled: true

- [x] 2. Amazon voucher

- Product name: Amazon voucher
- Product description: $50 Amazon voucher
- Quantity: 100
- Product type: voucher
- Code: AMAZ50
- Prices:
Price1: Currency - DEMO, amount - 10
Price2: Currency - TXBT, amount - 0.005
- Enabled: true

### Notification service

- [x] 1. Bulk add all email and SMS templates

**Comment by Cupofassam** [comment]
This is a reminder that we also need to create a user in the company in the `user` group - details to follow soon. We'll need to create the email address for it.

**Comment by Cupofassam** [comment]
Feedback to change:

- [ ] 1. For groups `user` and `merchant` please make the tiers as follows:

Tier 1 | Tier 2 | Tier 3
-- | -- | --
--- | Basic | Intermediary | Advanced
--- | First name, Last name | First name, Last name, Verified email | First name, Last name, Nationality, Birthdate, Verified email, Identity number, Verified mobile, Verified identity, Verified address

- [ ] 2. For groups `user` and `merchant` please remove all limits

**Comment by Cupofassam** [comment]
M, just so you know, this seems to be getting stuck for me, not sure if it's because it's unfinished.

![image](https://user-images.githubusercontent.com/22153546/53530869-06b0dd00-3afa-11e9-84e4-6ebe0f2a578b.png)

Those are the last things that get called, but my page still sits on the loader saying my demo is being set up.

the last url it hits is Request URL: https://api.rehive.com/3/admin/services/80/

**Comment by Cupofassam** [comment]
Noticed that when trying to set the Stellar testent service setup as true it is throwing some authentication bugs because the calls are happening before it's done. Setup a flag to ensure that the Stellar testnet has been activated once all of its setup calls are done.

**Comment by Cupofassam** [comment]
Cool, noticed some errors in my issue and some bugs, here's my feedback:

- [ ] 1. Major thing I forgot to add - Group permissions! Admin and service are as normal. In the tables below a ✓ means they need to have that permission. I'm only going to write out the Admin permissions. 

### All groups need ALL User permissions

`merchant`:

All user permissions, no admin permissions.

`user`:

All user permissions, no admin permissions.

`manager`:

Event | Admin VIEW | Admin ADD | Admin CHANGE | Admin DELETE 
-- | -- |-- | -- | -- 
Access control rule | ✓ |   |   |   |  
Account | ✓ |   |   |   |   
Address | ✓ | ✓ | ✓ | ✓ |  
Bank account | ✓ | ✓ | ✓ | ✓ |
Currency | ✓ |   |   |   |  
Company | ✓  |   |   |   |  
Crypto account | ✓ | ✓ | ✓ | ✓ |
Document | ✓ | ✓ | ✓ | ✓ |
Email | ✓ | ✓ | ✓ | ✓ |
Group | ✓ |   |   |   |  
MFA | ✓ |   |   |   |  
Mobile | ✓ | ✓ | ✓ | ✓ |
Notification | ✓ |   |   |   |  
Request | ✓ |   |   |   |  
Service | ✓ |   |   |   |  
Token | ✓ |   |   |   |  
Transaction | ✓ |   |   |   |  
Transaction subtypes | ✓ |   |   |   |  
User | ✓ | ✓ | ✓ | ✓ |
Webhook | ✓ |   |   |   |  

`support`:

Event | Admin VIEW | Admin ADD | Admin CHANGE | Admin DELETE 
-- | -- |-- | -- | -- 
Access control rule |   |   |   |   |  
Account | ✓ |   |   |   |  
Address | ✓ | ✓ | ✓ | ✓ |  
Bank account | ✓ | ✓ | ✓ | ✓ |
Currency | ✓ |   |   |   |  
Company |   |   |   |   |  
Crypto account | ✓ | ✓ | ✓ | ✓ |
Document | ✓ | ✓ | ✓ | ✓ |
Email | ✓ | ✓ | ✓ | ✓ |
Group | ✓ |   |   |   |  
MFA |   |   |   |   |  
Mobile | ✓ | ✓ | ✓ | ✓ |
Notification |   |   |   |   |  
Request |   |   |   |   |  
Service |   |   |   |   |  
Token |   |   |   |   |  
Transaction | ✓ | ✓ |   |   |  
Transaction subtypes | ✓ |   |   |   |  
User | ✓ | ✓ | ✓ | ✓ |
Webhook |   |   |   |   |  

- [ ] 2. Please update 2 group descriptions:

`support`: Support have limited access to make transactions from their own operational account, view and verify user data. Support do not have access to system configurations.

`manager`: Managers are able to make transactions from their own operational account, and view and verify user data. Managers do not have access to system configurations.

 - [ ] 3. Admin and Service groups don't have descriptions added. I know the Platform creates those groups for you so you'll just have to update the descriptions.

`admin`: Admin users have full access to all aspects of the company.

`service`: Services have access to specific permissions required for each service.

- [ ] 4. Change the name of the default and primary account for the group `user` - instead of `wallet` please name it `default`.

- [ ] 5. Rewards service setup has a few bugs:

- `Just for Joining` campaign - please change the event to `user_create`
- `First 250 users` campaign - Update the Campaign description to: `The first 250 users to claim this reward get an additional 10 DEMO tokens.`
- `First 250 users` campaign - Change the amount to 10

- [ ] 6. Product service, there seems to be a typo in the price for the `DEMO` price on the Steam voucher, it's 0.5 instead of 5.

**Comment by Dblaze47** [comment]
Cannot change the descriptions of Admin and Service. I returns a bad request and this error:

**Comment by Cupofassam** [comment]
Hey M

For the `mass_pay` subtypes credit and debit, please change this to `mass_send` for both

**Comment by Cupofassam** [comment]
After the subtypes have been created we're going to tell the Stellar service which ones to use:

https://stellar-testnet.services.rehive.io/redoc/#operation/admin_company_configuration_partial_update

This api shows all the fields. The subtypes can be any subtypes that exist in that company on Rehive. Match them up like this:

Stellar subtype setting | subtype
--- | ---
 "transaction_credit_subtype" | "deposit"
  "transaction_debit_subtype" | "withdraw"
  "transaction_fund_subtype" | "fund"
  "transaction_issue_subtype" | "issue"
  "transaction_fee_subtype" | "fee"

Do the same for bitcoin, here is the api https://bitcoin-testnet.services.rehive.io/redoc/#operation/admin_company_configuration_partial_update

Bitcoin subtype setting | subtype
--- | ---
 "transaction_credit_subtype" | "deposit"
  "transaction_debit_subtype" | "withdraw"
  "transaction_fund_subtype" | "fund"

**Comment by Cupofassam** [comment]
Running into 2 bugs :(

- [ ] 1. This one is a blocker - getting a 400 error and then the setup hangs. I have asked Connor to look into it and comment in the chat with all 3 of us on Slack, let's see what he says. My suspicion is it's not funding because it's already funded or something - did his change where he made the hot wallet the same as the warm wallet affect how we do the setup here?

```
Request URL: https://friendbot.stellar.org/?addr=GAPUB3X2AVZJV5UI76XMJSNH7ZQRHIKLLIQO3IOFV7VKVPEGNTP7TWB3
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 54.82.111.185:443
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Origin: http://localhost:3000
Connection: keep-alive
Content-Length: 909
Content-Type: application/problem+json; charset=utf-8
Date: Mon, 04 Mar 2019 23:57:32 GMT
Vary: Origin
Provisional headers are shown
Accept: application/json, text/plain, */*
Origin: http://localhost:3000
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
addr: GAPUB3X2AVZJV5UI76XMJSNH7ZQRHIKLLIQO3IOFV7VKVPEGNTP7TWB3
```

- [ ] 2. I noticed on my one test company that I could not add any prices to my product and no currency to my order. I know that the product service gets the currency list at the time of its creation and then we use that to add prices, currencies to orders etc. I thought we might be adding the product service before we added bitcoin or stellar but when I did tests stellar and bitcoin were added first before product (or is it done async so the currencies haven't had time to create yet?). 

Not sure what the solve is for #2 - maybe we should just explicitly add TXLM and TXBT currencies as part of the set up instead of relying on the services?

**Comment by Dblaze47** [comment]
For task - [x] 2. the currencies are being added before the Product service, and I have also to setup the Product service to restarted after Bitcoin and Stellar testnet are configured to make the currencies available. For my test companies, I did not face this problem. Maybe try with another new company?

**Comment by Cupofassam** [comment]
Product issue seems to have gone away.

Still 3 outstanding issues though:

- [ ] 1. Product service, there seems to be a typo in the price for the DEMO price on the Steam voucher, it's 0.5 but it should be 5.

- [ ] 2. For both Reward campaigns, the admin's operational account should be the reward account, but neither of the campaigns have an associated account.

- [ ] 3. I think you're doing this already but let's increase it - credit the admin's operational account with 7500 DEMO currency.

**Comment by Cupofassam** [comment]
MERGE ITTTTT 👌
