### ISSUE TITLE
Make all pop-up disappear when clicking outside of them

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#45]
Hey Aquib,

Please make all pop-ups disappear when clicking outside of them. Some currently do this but a couple don't such as the Filters and Columns buttons on the Users page. 

Thx!

**Comment by AquiburRKhan** [comment]
Doing it in issue30 as that branch has the column filters

**Comment by AquiburRKhan** [comment]
Did this in issue30 , did it for `Columns` but not `Filters` as there is the email filter where typeahead search is implemented, and everytime you click on the selection , the whole filter div disappears as it thinks you clicked outside of the div
