### ISSUE TITLE
Buggy spacing in Stellar ext

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#455]
Hey M

- [ ] 1. In the Stellar Testnet extension (and probably Stellar extension) please move Low balance percentage slightly to the right so that the total doesn't sit on a new line on a small screen:

![image](https://user-images.githubusercontent.com/22153546/53915165-1f744200-4068-11e9-8c15-f50307530730.png)

**Comment by Dblaze47** [comment]
This was already fixed on this issue:
