### ISSUE TITLE
Update login/register page spacing

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#470]
Hey M

On the login / register pages please make the following changes:

- [x] 1. Move the Log in and Register buttons more to the left, so that they are equally far from the right as they are from the top.

- [ ] 2. Replace the logo with the one you see when you log in to the Dashboard (with the hive logo)

- [x] 3. Move the logo more to the right so that it is as equally far from the left as it is from the top.

**Comment by Dblaze47** [comment]
Tasks - [ ] 1 & [ ] 3 has been covered in issue505

**Comment by Cupofassam** [comment]
Didn't realise this was a duplicate issue, closing this and moving all feedback to https://github.com/rehive/dashboard-angular/issues/505
