### ISSUE TITLE
Add user identifier when no email address  or mobile number when making a transaction

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#48]
Hey Aquib,

I tried to credit a user who had no email address's account. However, user email is a required field when making a transaction:

![image](https://user-images.githubusercontent.com/22153546/37425876-a3c230c6-27cd-11e8-986a-009ba773a77a.png)

If a user has no email address or mobile, please populate the User field with the user identifier automatically (I got here by clicking on "credit" in a user's account).

**Comment by AquiburRKhan** [comment]
@Cupofassam Please pull branch issue48 to test :)

**Comment by Cupofassam** [comment]
Happy with this :)
