### ISSUE TITLE
Bank Accounts update

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#49]
Hey AQ,

Please change how bank accounts work. Currently there's no place listing them and we can't add a currency to them.

Please work on this first thing :) Thanks!

![image](https://user-images.githubusercontent.com/22153546/37492184-17ccc1a8-28a9-11e8-9383-e1b19a197285.png)

Add bank account pop-up:

![image](https://user-images.githubusercontent.com/22153546/37492208-31cefcf6-28a9-11e8-88ae-9b72da1b6902.png)

Edit bank account pop-up:

![image](https://user-images.githubusercontent.com/22153546/37492220-3df2733c-28a9-11e8-81aa-e39b0720b693.png)

**Comment by Cupofassam** [comment]
Bank Accounts List
POST https://api.rehive.com/3/admin/bank-accounts/ (edited)

PATCH/PUT https://api.rehive.com/3/admin/bank-accounts/{id}/
Currencies list: 
GET https://api.rehive.com/3/admin/bank-accounts/{id}/currencies/
POST https://api.rehive.com/3/admin/bank-accounts/{id}/currencies/
DELETE https://api.rehive.com/3/admin/bank-accounts/{id}/currencies/{code}/

**Comment by Cupofassam** [comment]
Thanks Aquib,

Looks good to me except for 1 issue. On the bank where the bank accounts are listed only Bank name and Account number are showing. Please show the following info in the following order:

Bank name
Account name/holder
Account number
Currencies

**Comment by AquiburRKhan** [comment]
doing this in master

**Comment by Cupofassam** [comment]
Doesn't look great on a 13" screen:

![image](https://user-images.githubusercontent.com/22153546/37656241-2bf750bc-2c50-11e8-8f19-cbc66885f428.png)

- You can name it "Account name" instead of "Account name/holder".
- The 4 info columns can move more to the right
- Edit and delete are sitting weirdly

**Comment by Cupofassam** [comment]
Much better 👍

**Comment by Cupofassam** [comment]
Hey Aquib,

There is an error when a user has no bank accounts - when navigating there it just loads infinitely.

**Comment by Cupofassam** [comment]
Happy with the fix, pls merge :)
