### ISSUE TITLE
Move logo and buttons on login/register pages

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#505]
Hey Manosh

Please move the Rehive logo to the right and move the login and register buttons to the left, such that they are equally far from the left/right as they are from the top.

![image](https://user-images.githubusercontent.com/22153546/55628664-9577e000-57b1-11e9-9e37-f91674e5bdf1.png)

**Comment by Dblaze47** [comment]
Also replace the logo with the one seen when you log in to the Dashboard (with the hive logo).
Referring to task 2 of this issue: #470

**Comment by Cupofassam** [comment]
Didn't realise this was a duplicate issue, closing this :P

https://github.com/rehive/dashboard-angular/issues/470

**Comment by Cupofassam** [comment]
Hey M,

Oops, I didn't mean swap the buttons and the logo :P I just want the spacing ontop and on the side to be the same.

I think we can still use the Rehive logo with the hive pic

**Comment by Cupofassam** [comment]
👍
