### ISSUE TITLE
Cookie too large - Part 1

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#52]
Hey Aquib,

This "Request Header or Cookie too large" error is happening a lot lately.  I want to tackle the problem in 2 parts, this issue is for the first part.

1. Please figure out which cookie is becoming too big, why it's becoming so big, and find a quick fix for this. (We will do the move to local storage in part 2). We found cookies which were quite big (4kb which is big for a cookie).

Please check this out first thing, thanks :)

**Comment by AquiburRKhan** [comment]
Joshua was right, the table columns saving cookie is taking too much space , transaction table is 3001 byte and user table is 2628 table, switching these two to localstorage

**Comment by Cupofassam** [comment]
What all is being saved in those cookies? I know columns selection is part of it - please pop a quick list of what is being stored here

**Comment by AquiburRKhan** [comment]
Things saved in cookies are: 
TOKEN
company_identifier
transaction table columns
user table columns

**Comment by Cupofassam** [comment]
Working well, please merge :)
