### ISSUE TITLE
Adding a service - password popup tweaks

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#57]
Hi AQ,

We need 2 tweaks to the password pop up when adding a service.

https://dashboard.rehive.com/#/services/add

1. The label for the password is "Password:" with a : at the end. Please remove the colon :
2. When I enter my password, pressing enter does not submit the form, I have to manually press the add button which is quite annoying. Please allow the form to submit by pressing the enter button.

![image](https://user-images.githubusercontent.com/22153546/38527386-b3221b98-3c5a-11e8-89ab-28038603f540.png)

**Comment by AquiburRKhan** [comment]
Please delete bower components folder and node modules folder and then run npm install and then test it

**Comment by Cupofassam** [comment]
Will do

**Comment by Cupofassam** [comment]
Thanks Aquib, works great. 2 other small things I noticed and want to change:

1. Remove the ? from the end of the copy. It should just be

`Please enter your password to proceed.`

2. Remove the hint text copy, it's kinda pointless and repetitive.

**Comment by AquiburRKhan** [comment]
changed hint copy than removing it completely as it looks too empty

**Comment by Cupofassam** [comment]
Cool, merge pls :)
