### ISSUE TITLE
Onboarding - selecting lots of currencies styling issues

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#61]
Hi Aquib,

In the onboarding section, currencies page:

https://dashboard.rehive.com/#/company/setup/currency-setup

If a user selects lots/all of the currencies, it kind of breaks the styling (highlighted in yellow):

![image](https://user-images.githubusercontent.com/22153546/38527703-67ea5648-3c5c-11e8-9b25-4c23b43c9ca0.png)

Please make them wrap nicely within bounds. Obviously they will have to extend the length of the page and push down the save button.

**Comment by AquiburRKhan** [comment]
this seems to be fixed in the current master, dont know how, but its working, let me know if it breaks for you

**Comment by Cupofassam** [comment]
This is still an issue on live for some reason.

**Comment by AquiburRKhan** [comment]
Its still working for me in master, but I still added css to prevent the bug from happening, I guess we will know its fixed or not after deployment

**Comment by Cupofassam** [comment]
Nope, still happening :/

**Comment by Cupofassam** [comment]
Nevermind, it was because the deploy failed :P Working now.
