### ISSUE TITLE
Add pagination to currency listing page

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#62]
Hey A to the Q,

On the currencies page, it only shows a max of 15 currencies, even if you have added more than 15 to your company. Please add pagination to this page when there are more than 15 currencies. It can show the pagination as just 1 page if there are less than 15 currencies.

https://dashboard.rehive.com/#/currencies

**Comment by AquiburRKhan** [comment]
hey sam I fixed this , when I noticed it , but right now I am showing all the currencies in the same page , should I make it paginated with 15 currencies each page or just show all the currencies on one page which a user may have to scroll a lot ?

**Comment by Cupofassam** [comment]
Paginated with 15 currencies per page pls :)

**Comment by Cupofassam** [comment]
This is good, but this back to top thing is getting all up in the pagination's face:

![image](https://user-images.githubusercontent.com/22153546/38894826-a9f11b48-428e-11e8-9a03-fb4e1e11faf2.png)

Can we make the back to top button always sit lower than whatever is at the end of a page?

**Comment by Cupofassam** [comment]
:+1
