### ISSUE TITLE
Add 2 new filter options for transactions

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#67]
Hey Aquib,

We would like to add 2 more filter options for transactions.

1. Filter by whether transactions have a source ID - boolean
2. Filter by whether transactions have a destination ID - boolean

You can call them "Has destination txn id" and "Has source txn id"

**Comment by AquiburRKhan** [comment]
what are the filter fields ?

**Comment by Cupofassam** [comment]
destination_transaction = true/false
source_transaction = true/false

**Comment by Cupofassam** [comment]
@OdinsPlasmaRifle

**Comment by OdinsPlasmaRifle** [comment]
It is correct. Some transfers are to users who don't exist, so the destination transaction has no ID yet because it hasn't been attached to a user yet.

**Comment by AquiburRKhan** [comment]
ah ok :+1:

**Comment by Cupofassam** [comment]
![image](https://user-images.githubusercontent.com/22153546/38895307-00139964-4290-11e8-93bc-5bb77c1a75d2.png)

I'm guessing the first checkbox is to select the filter and the second is to select whether the filter is true/false. Can we change it so that selecting the first checkbox always means "filter if x = true", so filter by transactions that are only source = true etc. I  thought about it more and I can't see a useful scenario where we would want to see transactions that don't have a source ID - it would just give us half transfers and then all other transactions, which doesn't tell us much.

**Comment by Cupofassam** [comment]
Anyway we can hide the 2nd checkbox entirely?

![image](https://user-images.githubusercontent.com/22153546/38936364-e1be1426-4320-11e8-9421-d4fe2e1c2b29.png)

**Comment by Cupofassam** [comment]
Also please change the field copy to

`Has destination txn`

and

`Has source txn`

**Comment by Cupofassam** [comment]
👍
