### ISSUE TITLE
Groups - tweaks

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#68]
Hey AQ,

1. In Groups, it shows me the total number of users, and then a breakdown of total active users vs deactivated users. However in this one group I Have 17 users,0 active users and 0 deactivated users. I don't think any of my users are deactivated but the active users should show 17. Please look into this.

![image](https://user-images.githubusercontent.com/22153546/38672997-1f6f6c5a-3e50-11e8-8ee1-1e5428ed327c.png)

2. The copy reads "Activated" users - please change this to "Active" users.

3. For the group name in the image above, please switch to using the group label rather than the group name.

4. When hovering over the default/public checkboxes, the line height in the message looks a little big - what is the line height? Can we adjust it to the same line height we use throughout the rest of the dashboard?

![image](https://user-images.githubusercontent.com/22153546/38673197-e7c272b0-3e50-11e8-8b01-b9c75dd28deb.png)

**Comment by AquiburRKhan** [comment]
Using group name is risky as `label` is not a required field

**Comment by Cupofassam** [comment]
Happy to leave 3 out since label is not required.

For number 4, the spacing is slightly too little now :P Please increase slightly but not as much as before.

**Comment by Cupofassam** [comment]
Perfect, happy with this, you can merge :)
