### ISSUE TITLE
Update deprecated API field

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#69]
Hey Aquib,

`date_joined` is no longer being used. 

The correct field and filter to use now is `created` and/or `updated`.

Please update this in the dashboard.

**Comment by AquiburRKhan** [comment]
is `date_joined__gt` and `date_joined__lt` now `created__gt` and `created__gt`

**Comment by Cupofassam** [comment]
yes

**Comment by Cupofassam** [comment]
and this change should be made in the columns too

**Comment by Cupofassam** [comment]
👍
