### ISSUE TITLE
Columns still use date joined instead of created

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#81]
Hey AQ,

We updated the user filter to show Created, but did not update the columns to Created. Please update from Date joined to Created :)

This is part of the current sprint

![image](https://user-images.githubusercontent.com/22153546/39017921-dd6cde16-4424-11e8-9a92-f07e402fab09.png)

**Comment by AquiburRKhan** [comment]
I think this is an issue due to not hard refreshing , as I cant find any `Date joined` in the code, let me know if its still there after hard refreshing

**Comment by Cupofassam** [comment]
Hey, please add code that if it sees `date_joined` instead of `created` in column names it replaces it. We can eventually remove this.
