### ISSUE TITLE
Fix group users heading being saved in cookie and add updated field and filter

### ISSUE THREAD

**Issue by AquiburRKhan** [rehive/dashboard-angular#83]
group users headings should be saved like it is being in users, in localstorage and also add the `updated` field and filter

**Comment by Cupofassam** [comment]
Thanks Aquib, how can I test this? I went to the page but didn't see anything extra stored in local storage:P

**Comment by AquiburRKhan** [comment]
If you make any changes to hiding and showing the column .... You should see company identifier + group name + userstable saved in local storage and you should also test whether update filter is working or not and the update field is in the table or not

**Comment by Cupofassam** [comment]
👍
