### ISSUE TITLE
Switch to using javascript SDK for API handling

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#87]
Use the javascript SDK maintained by Rehive in your package.json and npm installs.

Switch all API usage to use the SDK when making calls.

If you notice any bugs in the SDK, let @TarCode know.

https://github.com/rehive/rehive-javascript

**Comment by Cupofassam** [comment]
Currency page:

- When I filter by unit, I get repeat units. i.e. I see dollar multiple times. It seems correct that there are multiple currencies with this unit, but the filter by is not being combined into one thing. I also see an error on live when I compare the same company - there is no dollar unit available in the unit filter. It's limiting it to only 15 units I think.
![image](https://user-images.githubusercontent.com/22153546/42044619-c2b752ca-7af9-11e8-88fc-da16c91fb50b.png)

- There is a problem when adding a custom currency. The unit added does not get added to the available units to filter by. It just adds a blank space to the units list. When I filter by that it shows me my last added custom currency (the unit I chose was KAP). I added another one, with a different unit (ZAP). When I filtered by the blank space at the top of the unit list, ZAP showed up and KAP no longer showed up. KAP also did not show up anywhere in the unit filter list. When I hard refreshed, the blank space was gone and KAP and ZAP showed up in the units filter. I added another custom currency. Its unit did not show up in the unit filter and no blank space appeared either. I hard refreshed and my new custom currency (LAK) showed up at the top of the unit filter list.

- Can we please order the unit filter list alphabetically

**Comment by Cupofassam** [comment]
1. When filtering by unit on currencies, please make the drop down longer, it cuts off weirdly right now:
![image](https://user-images.githubusercontent.com/22153546/42377777-144968d6-8125-11e8-9913-3c6211429994.png)
2. For unit filtering can we start at the top of the alphabet rather than the bottom.
3. I'm getting this error when trying to do several things throughout the dashboard. It happened when I tried to add a new group (name "non stop party", same thing with a group named "sop") and also happened when I tried to add a new custom currency (all values were "keo") 

![image](https://user-images.githubusercontent.com/22153546/42377848-5b559880-8125-11e8-93e6-0005166cec51.png)

Error:  

![image](https://user-images.githubusercontent.com/22153546/42377841-53d0d1ce-8125-11e8-8620-67ac33fb93e8.png)

4. I searched "test1" in the top search bar in test_company_1 and it just showed the loader for ages:

![image](https://user-images.githubusercontent.com/22153546/42378345-46cec5ce-8127-11e8-9999-49e275474650.png)

Don't seem to be any console or network errors.

5. Sometimes when I hard refresh or normal refresh, the company info disappears from the header. IfI go to a new page it comes back. Refreshing that page then causes the error to happen again.

![image](https://user-images.githubusercontent.com/22153546/42378561-f9cab32c-8127-11e8-803b-2dba6412bdc0.png)

![image](https://user-images.githubusercontent.com/22153546/42378568-01216d78-8128-11e8-86bc-abb3ba8fb310.png)

6. Can't delete an added bank account - need to take into account archiving here.

7. This is something that should be fixed when we merge master into this branch but just noting it - added services are still  in the list to add services.

**Comment by AquiburRKhan** [comment]
I could did not reproduce the error in point 3 , I created the groups with those names and the custom currency , and for point number 6 , How do I archive a bank account or currency ? and which assets can be archived ?

**Comment by Cupofassam** [comment]
Errors:
1) transactions erroring out, 415 error code, need to force content-type in sdk, happened once but now its fixed, me and Taariq are keeping an eye on it
2) In new transactions modal , user tooltip only appearing after clicking something after the email loads
3) after editing transaction, the modal spinner spins indefinitely until clicked
4) user address, user documents , no spinner when adding
5) `view transaction` does not work in user accounts, but that is fixed in another issue where I put the column filters to user transactions, going to test this properly after merging that issue to master and then master to the sdk branch
6) Group users table, reassign modal , button is disabled and doesnt show current selected group of user in dropdown initially
7) group account configuration , adding , label doesnt auto fill when filling name (edited)
