### ISSUE TITLE
Add account reference number to main header search

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#9]
Add account reference number to the main header search.

e.g. CF8LQJJ8P9 - when I search for this, the relevant user should appear.

Same functionality that was added to the filter functionality for users.

**Deadline: End of day Thursday**

**Comment by AquiburRKhan** [comment]
right now I am having to check whether the search text is an email or a mobile number , if its neither of those two I am assuming its a transaction ID
so If I add account reference to that , I dont know how we can differentiate what the search text is and which filter to use ?
so in the short term I have added the account reference filter in the users page

**Comment by Cupofassam** [comment]
Thanks Aquib - discussed this with Helghardt and Josh. It's fine to just have account reference in the filters on the user page for now. Longer term we will look at improving the API so you can implement this stuff easier without hacking it. 

Putting this issue on hold for now.

**Comment by Cupofassam** [comment]
Closing this issue, it's being covered in #412
