### ISSUE TITLE
Move account reference into 'advanced options' when adding account

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#93]
Hey Aquib,

When users add an account, we want to hide the Reference field behind an 'Advanced options' link. In general we don't really want users amending this but they can if they really want to.

Please change the add account modal to look like this:

![image](https://user-images.githubusercontent.com/22153546/39138671-c74c1db4-4720-11e8-9e61-f4b58683b55e.png)

When a user clicks on the Advanced options link, the Reference field should appear underneath Advanced options, above the Close and Add buttons.

![image](https://user-images.githubusercontent.com/22153546/39138803-dc7ec4b6-4720-11e8-96ff-26e6a4ab56a3.png)

I want to use the information i here like we did in onboarding. The text for the tooltip will be:

`Rehive will auto-generate a unique reference for an account. If you prefer to create your own reference you can enter it below. References are generally used for identifying deposits from users.`

**Comment by Cupofassam** [comment]
Thanks Aquib :) It works well, we're just missing the informational i and it's copy.

**Comment by AquiburRKhan** [comment]
oh sorry , missed that part

**Comment by Cupofassam** [comment]
👍
